import Head from 'next/head'

import styles from '../styles/Home.module.css'

import useQuestion from '../hooks/useQuestion';

import { useEffect } from 'react';

import ReactLoading from 'react-loading';

import Link from 'next/link';

import Router from 'next/router';

export default function Home() {

  const {
    questions,
    loading,
    result,
    newGame,
  } = useQuestion();

  useEffect(() => {
    if(!questions) {
      return Router.push('/');
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Quiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {loading ? <ReactLoading type={'spin'} height={'3rem'} width={'3rem'} /> : (
        <div className={styles.content}>
          <h1>Resultado Final</h1>

          <div className={styles.row}>
            <div className={styles.column}>
              <div className={styles.circle} style={{ background: '#ffaf40' }}>{questions.length}</div>
              <span>Perguntas</span>
            </div>

            <div className={styles.column}>
              <div className={styles.circle} style={{ background: '#3ae374' }}>{result}</div>
              <span>Corretas</span>
            </div>

            <div className={styles.column}>
              <div className={styles.circle} style={{ background: '#ff3838' }}>{ Math.round((result / questions.length) * 100) }%</div>
              <span>Porcentagem</span>
            </div>
          </div>

          <Link href={`/quiz`} passHref>
            <button onClick={newGame}>Tentar novamente</button>
          </Link>
        </div>
      )}
    </div>
  )
}