import Head from 'next/head'

import styles from '../styles/Home.module.css'

import useQuestion from '../hooks/useQuestion';

import Link from 'next/link';

export default function Home() {

  const {
    newGame,
  } = useQuestion();

  return (
    <div className={styles.container}>
      <Head>
        <title>Quiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.content}>
        <Link href={`/quiz`} passHref>
          <button onClick={newGame}>Iniciar Quiz</button>
        </Link>
      </div>
    </div>
  )
}