import styles from '../styles/Quiz.module.css'

import Head from 'next/head'

import useQuestion from '../hooks/useQuestion';

import { Fragment, useEffect, useState } from 'react';

import Router from 'next/router';

import ReactLoading from 'react-loading';

import Countdown from '../components/Countdown';

import Flip from '../components/Flip';

export default function Question() {

  const {
    indexQuestion,
    setIndexQuestion,
    questions,
    loading,
    result,
    setResult,
    getQuestions
  } = useQuestion();

  const [selectedAnswer, setSelectedAnswer] = useState();

  const [isAnswered, setIsAnswered] = useState(false);

  const [reset, setReset] = useState(0);

  function checkAnswer(answer) {
    if (isAnswered) {
      return alert('Você não pode mudar sua resposta, passe para a proxima pergunta');
    }

    answer.correct && setResult(result + 1);
    setSelectedAnswer(answer);
    setIsAnswered(true);
  }

  function nextQuestion() {
    setIsAnswered(false);

    if (indexQuestion === questions.length - 1) {
      setIndexQuestion(0);
      return Router.push('/end');
    }

    setIndexQuestion(indexQuestion + 1);
    setReset(prevKey => prevKey + 1)
  }

  useEffect(() => {
    getQuestions();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Quiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {loading ? <ReactLoading type={'spin'} height={'3rem'} width={'3rem'} /> : (
        <Fragment>
          <h1>{questions[indexQuestion].title}</h1>

          <p>Pergunta {indexQuestion + 1} de {questions.length}</p>

          <Countdown nextQuestion={nextQuestion} reset={reset} />

          <div className={styles.answers}>
            {questions[indexQuestion].answers.map((answer, index) => (
              <div key={index} onClick={() => checkAnswer(answer)}>
                <Flip
                  answer={answer}
                  isAnswered={isAnswered}
                  selectedAnswer={selectedAnswer}
                />
              </div>
            ))}
          </div>

          <button onClick={nextQuestion}>Próxima</button>
        </Fragment>
      )}

    </div>
  );
}
